In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train KNN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))



Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [1]:
import pandas as pd
import sklearn

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
df=pd.read_csv('500hits.csv',encoding='latin-1')

In [4]:
df.head(4)

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1

In [5]:
X=df.drop(columns=['PLAYER','HOF'])#Freature or input data 

In [6]:
y=df['HOF']

In [8]:
X.head(3)

YRS     G     AB     R     H   2B   3B   HR   RBI    BB   SO   SB   CS  \
0   24  3035  11434  2246  4189  724  295  117   726  1249  357  892  178   
1   22  3026  10972  1949  3630  725  177  475  1951  1599  696   78   31   
2   22  2789  10195  1882  3514  792  222  117   724  1381  220  432  129   

      BA  
0  0.366  
1  0.331  
2  0.345

In [10]:
X.shape

(465, 14)

In [11]:
y.shape

(465,)

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=11,test_size=0.2)

In [13]:
X_train.shape

(372, 14)

In [15]:
y_train.shape

(372,)

In [16]:
X_test.shape

(93, 14)

In [17]:
X_train.describe().round(2)

YRS        G        AB        R        H      2B      3B      HR  \
count  372.00   372.00    372.00   372.00   372.00  372.00  372.00  372.00   
mean    17.01  2046.52   7526.08  1154.13  2177.99  382.51   78.09  202.64   
std      2.66   351.23   1302.41   291.31   426.62   97.17   48.80  141.73   
min     11.00  1331.00   4981.00   651.00  1660.00  177.00    3.00    9.00   
25%     15.00  1797.50   6507.50   936.00  1838.00  312.00   41.00   79.75   
50%     17.00  1992.00   7237.00  1099.00  2080.50  367.00   67.00  185.50   
75%     19.00  2245.50   8198.25  1305.00  2383.75  436.25  108.00  293.25   
max     26.00  3308.00  12364.00  2295.00  4189.00  792.00  309.00  755.00   

           RBI       BB       SO       SB      CS      BA  
count   372.00   372.00   372.00   372.00  372.00  372.00  
mean    901.07   780.10   850.32   196.93   58.99    0.29  
std     484.37   327.45   472.92   185.59   49.32    0.02  
min       0.00   239.00     0.00     7.00    0.00    0.25  
25%     645.00   536.50   448.00    64.50   23.00    0.27  
50%     977.50   719.00   844.00   141.00   52.00    0.29  
75%    1218.50   961.25  1234.25   285.50   84.00    0.30  
max    2297.00  2190.00  1936.00  1406.00  335.00    0.37

In [20]:
X_train.head(3)

YRS     G    AB    R     H   2B   3B   HR   RBI   BB    SO   SB   CS  \
289   18  2028  7298  873  1993  284   40  325  1163  620  1313   20   38   
288   13  1836  6826  856  1996  392  117   43   402  513   360  247  108   
350   14  1799  6373  876  1854  282   64   49   630  844   627   37   51   

        BA  
289  0.273  
288  0.292  
350  0.291

In [19]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)

In [27]:
X_trainscaled=pd.DataFrame(X_train,columns=['YRS',	'G',	'AB',	'R',	'H',	'2B',	'3B',	'HR',	'RBI',	'BB',	'SO',	'SB',	'CS',	'BA'])

In [30]:
X_trainscaled.round(3).head(3)

YRS      G     AB      R      H     2B     3B     HR    RBI     BB  \
0  0.372 -0.053 -0.175 -0.966 -0.434 -1.015 -0.782  0.864  0.541 -0.490   
1 -1.508 -0.600 -0.538 -1.025 -0.427  0.098  0.798 -1.128 -1.032 -0.817   
2 -1.132 -0.706 -0.887 -0.956 -0.760 -1.036 -0.289 -1.086 -0.560  0.195   

      SO     SB     CS     BA  
0  0.980 -0.955 -0.426 -0.768  
1 -1.038  0.270  0.995  0.135  
2 -0.473 -0.863 -0.162  0.087

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
nor=MinMaxScaler()#b/w 0 to 1
X_train=nor.fit_transform(X_train)
X_trainscaled=pd.DataFrame(X_train,columns=['YRS',	'G',	'AB',	'R',	'H',	'2B',	'3B',	'HR',	'RBI',	'BB',	'SO',	'SB',	'CS',	'BA'])

In [35]:
X_trainscaled.head(3)

YRS         G        AB         R         H        2B        3B  \
0  0.466667  0.352554  0.313829  0.135036  0.131673  0.173984  0.120915   
1  0.133333  0.255438  0.249898  0.124696  0.132859  0.349593  0.372549   
2  0.200000  0.236722  0.188541  0.136861  0.076710  0.170732  0.199346   

         HR       RBI        BB        SO        SB        CS        BA  
0  0.423592  0.506313  0.195284  0.678202  0.009292  0.113433  0.225000  
1  0.045576  0.175011  0.140441  0.185950  0.171551  0.322388  0.383333  
2  0.053619  0.274271  0.310097  0.323864  0.021444  0.152239  0.375000

In [36]:
df['HOF'].unique()

array([1, 0, 2])